const crypto = require('crypto');
const path = require('path');
const fs = require('fs');
const { spawn, spawnSync } = require('child_process');

const ROOT = path.resolve(__dirname, '..');
const ENV_FILE = path.join(ROOT, '.env');
const MONGO_STATE = path.join(__dirname, '.mongo-memory.state.json');

function randomHex(bytes) {
  return crypto.randomBytes(bytes).toString('hex');
}

function ensureEnvFile() {
  if (!fs.existsSync(ENV_FILE)) {
    const defaults = [
      `# Auto-generated by setup-mongo.cjs on ${new Date().toISOString()}`,
      `MONGODB_URI=`,
      `REDIS_URL=`,
      `JWT_SECRET=${randomHex(32)}`,
      `PORT=3000`,
      `ENCRYPTION_KEY=${randomHex(16)}`,
      `__CAMPUS_INMEMORY_REDIS=1`,
      ``,
    ].join('\n');
    fs.writeFileSync(ENV_FILE, defaults, 'utf8');
    console.log('[setup] Created .env with JWT_SECRET, ENCRYPTION_KEY, and in-memory Redis enabled');
  } else {
    const current = fs.readFileSync(ENV_FILE, 'utf8');
    const entries = new Map(
      current
        .split(/\r?\n/)
        .filter((l) => l && !l.startsWith('#') && l.includes('='))
        .map((l) => {
          const idx = l.indexOf('=');
          return [l.slice(0, idx).trim(), l.slice(idx + 1).trim()];
        }),
    );
    let changed = false;
    if (!entries.has('JWT_SECRET') || !entries.get('JWT_SECRET')) {
      entries.set('JWT_SECRET', randomHex(32));
      changed = true;
    }
    if (!entries.has('ENCRYPTION_KEY') || !entries.get('ENCRYPTION_KEY')) {
      entries.set('ENCRYPTION_KEY', randomHex(16));
      changed = true;
    }
    if (!entries.has('__CAMPUS_INMEMORY_REDIS')) {
      entries.set('__CAMPUS_INMEMORY_REDIS', '1');
      changed = true;
    }
    if (!entries.has('PORT')) {
      entries.set('PORT', '3000');
      changed = true;
    }
    if (changed) {
      const out = [...entries.entries()].map(([k, v]) => `${k}=${v}`).join('\n') + '\n';
      fs.writeFileSync(ENV_FILE, out, 'utf8');
      console.log('[setup] Updated .env with missing secrets');
    } else {
      console.log('[setup] .env already configured');
    }
  }
}

function setEnvValue(key, value) {
  const current = fs.existsSync(ENV_FILE) ? fs.readFileSync(ENV_FILE, 'utf8') : '';
  const lines = current.split(/\r?\n/);
  let found = false;
  for (let i = 0; i < lines.length; i++) {
    const l = lines[i];
    if (!l || l.startsWith('#') || !l.includes('=')) continue;
    const idx = l.indexOf('=');
    const k = l.slice(0, idx).trim();
    if (k === key) {
      lines[i] = `${key}=${value}`;
      found = true;
      break;
    }
  }
  if (!found) lines.push(`${key}=${value}`);
  fs.writeFileSync(ENV_FILE, lines.join('\n') + '\n', 'utf8');
}

function readDotEnv() {
  const out = {};
  const current = fs.existsSync(ENV_FILE) ? fs.readFileSync(ENV_FILE, 'utf8') : '';
  for (const line of current.split(/\r?\n/)) {
    if (!line || line.startsWith('#') || !line.includes('=')) continue;
    const idx = line.indexOf('=');
    const k = line.slice(0, idx).trim();
    const v = line.slice(idx + 1).trim();
    out[k] = v;
  }
  return out;
}

async function waitForMongoState(timeoutMs = 120000) {
  const start = Date.now();
  while (Date.now() - start < timeoutMs) {
    if (fs.existsSync(MONGO_STATE)) {
      try {
        const s = JSON.parse(fs.readFileSync(MONGO_STATE, 'utf8'));
        if (s && s.uri) return s;
      } catch (_) {}
    }
    await new Promise((r) => setTimeout(r, 500));
  }
  throw new Error('MongoDB memory server did not write state file within timeout');
}

async function main() {
  ensureEnvFile();

  console.log('[setup] Starting MongoDB memory server (replica set) in background...');
  const mongoProc = spawn(
    process.execPath,
    [path.join(__dirname, 'dev-mongo.cjs')],
    {
      stdio: 'inherit',
      cwd: ROOT,
      detached: false,
    },
  );
  mongoProc.on('exit', (code) => {
    console.error(`[setup] dev-mongo exited with code ${code}`);
    process.exit(code ?? 1);
  });

  const state = await waitForMongoState();
  console.log(`[setup] MongoDB ready: ${state.uri}`);
  setEnvValue('MONGODB_URI', state.uri);

  const env = { ...process.env, ...readDotEnv() };

  console.log('[setup] Launching API + Dashboard (via concurrently)...');
  const child = spawn(
    /^win/.test(process.platform) ? 'npx.cmd' : 'npx',
    ['concurrently',
      '-n', 'mongo,api,dashboard',
      '-c', 'yellow,blue,green',
      `"REM Mongo (pid=${state.pid})"`,
      `"npm:dev:api"`,
      `"npm:dev:dashboard"`,
    ],
    { stdio: 'inherit', cwd: ROOT, env, shell: true },
  );
  child.on('exit', (code) => {
    try { process.kill(mongoProc.pid); } catch (_) {}
    process.exit(code ?? 0);
  });
}

main().catch((err) => {
  console.error('[setup] Fatal error:');
  console.error(err);
  process.exit(1);
});
